---
title: Ohiourisa.Github.Io
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
- scope:
  path: ""
  ty[e: events
  values:
    layout: default
name: Ohio Chapter of URISA
url: ''
baseurl: https://ohiourisa.github.io
permalink: "/:categories/:title/"
description: Ohio URISA Homepage - An officially recognized association of GIS Professionals
  in Ohio
author: Ohio URISA
header-img: world-large-inv-2.png
logo: ohurisa-logo.png
future: true
twitter: ohiourisa
github: ohiourisa
facebook: 216028668491458
address: PO BOX 282148
city: Columbus, OH 43228
include:
- _pages
exclude:
- node_modules
