name: Ohio URISA
url: ""
baseurl: ""
permalink: /:categories/:title/index.html
description: Ohio URISA Homepage - An officially recognized association of GIS Professionals in Ohio
author: Ohio URISA
twitter: ohiourisa
facebook:
exclude:
  - node_modules
